# Generated by Django 3.1.2 on 2020-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sat_fat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('trans_fat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fiber_carb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sugar_carb', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('protiens', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vitamins', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
