# Generated by Django 3.1.2 on 2020-10-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201031_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='fiber_carb',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='sat_fat',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='sugar_carb',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='trans_fat',
        ),
    ]
