# Generated by Django 3.1.3 on 2020-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201108_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeal',
            name='fooditem',
        ),
        migrations.AddField(
            model_name='usermeal',
            name='fooditem',
            field=models.ManyToManyField(to='user.FoodItem'),
        ),
    ]
