# Generated by Django 3.1.2 on 2020-11-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
