# Generated by Django 3.1.2 on 2020-11-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
