# Generated by Django 3.1.2 on 2020-11-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201123_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
